/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPatientIntakesIndexRouteImport } from './routes/_authenticated/patient-intakes/index'
import { Route as AuthenticatedPatientIntakesNewRouteImport } from './routes/_authenticated/patient-intakes/new'
import { Route as AuthenticatedSuppliesIndexRouteImport } from './routes/_authenticated/supplies/index'
import { Route as AuthenticatedSuppliesNewRouteImport } from './routes/_authenticated/supplies/new'
import { Route as AuthenticatedPatientIntakesIntakeIdIndexRouteImport } from './routes/_authenticated/patient-intakes/$intakeId/index'
import { Route as AuthenticatedPatientIntakesIntakeIdEditRouteImport } from './routes/_authenticated/patient-intakes/$intakeId/edit'
import { Route as AuthenticatedSuppliesItemIdIndexRouteImport } from './routes/_authenticated/supplies/$itemId/index'
import { Route as AuthenticatedSuppliesItemIdEditRouteImport } from './routes/_authenticated/supplies/$itemId/edit'
import { Route as ApiPublicHooksSendReorderEmailsRouteImport } from './routes/api/public/hooks/send-reorder-emails'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientIntakesIndexRoute =
  AuthenticatedPatientIntakesIndexRouteImport.update({
    id: '/patient-intakes/',
    path: '/patient-intakes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientIntakesNewRoute =
  AuthenticatedPatientIntakesNewRouteImport.update({
    id: '/patient-intakes/new',
    path: '/patient-intakes/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuppliesIndexRoute =
  AuthenticatedSuppliesIndexRouteImport.update({
    id: '/supplies/',
    path: '/supplies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuppliesNewRoute =
  AuthenticatedSuppliesNewRouteImport.update({
    id: '/supplies/new',
    path: '/supplies/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientIntakesIntakeIdIndexRoute =
  AuthenticatedPatientIntakesIntakeIdIndexRouteImport.update({
    id: '/patient-intakes/$intakeId/',
    path: '/patient-intakes/$intakeId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientIntakesIntakeIdEditRoute =
  AuthenticatedPatientIntakesIntakeIdEditRouteImport.update({
    id: '/patient-intakes/$intakeId/edit',
    path: '/patient-intakes/$intakeId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuppliesItemIdIndexRoute =
  AuthenticatedSuppliesItemIdIndexRouteImport.update({
    id: '/supplies/$itemId/',
    path: '/supplies/$itemId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuppliesItemIdEditRoute =
  AuthenticatedSuppliesItemIdEditRouteImport.update({
    id: '/supplies/$itemId/edit',
    path: '/supplies/$itemId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksSendReorderEmailsRoute =
  ApiPublicHooksSendReorderEmailsRouteImport.update({
    id: '/api/public/hooks/send-reorder-emails',
    path: '/api/public/hooks/send-reorder-emails',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/patient-intakes/new': typeof AuthenticatedPatientIntakesNewRoute
  '/supplies/new': typeof AuthenticatedSuppliesNewRoute
  '/patient-intakes/': typeof AuthenticatedPatientIntakesIndexRoute
  '/supplies/': typeof AuthenticatedSuppliesIndexRoute
  '/patient-intakes/$intakeId/edit': typeof AuthenticatedPatientIntakesIntakeIdEditRoute
  '/supplies/$itemId/edit': typeof AuthenticatedSuppliesItemIdEditRoute
  '/api/public/hooks/send-reorder-emails': typeof ApiPublicHooksSendReorderEmailsRoute
  '/patient-intakes/$intakeId/': typeof AuthenticatedPatientIntakesIntakeIdIndexRoute
  '/supplies/$itemId/': typeof AuthenticatedSuppliesItemIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/patient-intakes/new': typeof AuthenticatedPatientIntakesNewRoute
  '/supplies/new': typeof AuthenticatedSuppliesNewRoute
  '/patient-intakes': typeof AuthenticatedPatientIntakesIndexRoute
  '/supplies': typeof AuthenticatedSuppliesIndexRoute
  '/patient-intakes/$intakeId/edit': typeof AuthenticatedPatientIntakesIntakeIdEditRoute
  '/supplies/$itemId/edit': typeof AuthenticatedSuppliesItemIdEditRoute
  '/api/public/hooks/send-reorder-emails': typeof ApiPublicHooksSendReorderEmailsRoute
  '/patient-intakes/$intakeId': typeof AuthenticatedPatientIntakesIntakeIdIndexRoute
  '/supplies/$itemId': typeof AuthenticatedSuppliesItemIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/patient-intakes/new': typeof AuthenticatedPatientIntakesNewRoute
  '/_authenticated/supplies/new': typeof AuthenticatedSuppliesNewRoute
  '/_authenticated/patient-intakes/': typeof AuthenticatedPatientIntakesIndexRoute
  '/_authenticated/supplies/': typeof AuthenticatedSuppliesIndexRoute
  '/_authenticated/patient-intakes/$intakeId/edit': typeof AuthenticatedPatientIntakesIntakeIdEditRoute
  '/_authenticated/supplies/$itemId/edit': typeof AuthenticatedSuppliesItemIdEditRoute
  '/api/public/hooks/send-reorder-emails': typeof ApiPublicHooksSendReorderEmailsRoute
  '/_authenticated/patient-intakes/$intakeId/': typeof AuthenticatedPatientIntakesIntakeIdIndexRoute
  '/_authenticated/supplies/$itemId/': typeof AuthenticatedSuppliesItemIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audit'
    | '/dashboard'
    | '/settings'
    | '/patient-intakes/new'
    | '/supplies/new'
    | '/patient-intakes/'
    | '/supplies/'
    | '/patient-intakes/$intakeId/edit'
    | '/supplies/$itemId/edit'
    | '/api/public/hooks/send-reorder-emails'
    | '/patient-intakes/$intakeId/'
    | '/supplies/$itemId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/audit'
    | '/dashboard'
    | '/settings'
    | '/patient-intakes/new'
    | '/supplies/new'
    | '/patient-intakes'
    | '/supplies'
    | '/patient-intakes/$intakeId/edit'
    | '/supplies/$itemId/edit'
    | '/api/public/hooks/send-reorder-emails'
    | '/patient-intakes/$intakeId'
    | '/supplies/$itemId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/patient-intakes/new'
    | '/_authenticated/supplies/new'
    | '/_authenticated/patient-intakes/'
    | '/_authenticated/supplies/'
    | '/_authenticated/patient-intakes/$intakeId/edit'
    | '/_authenticated/supplies/$itemId/edit'
    | '/api/public/hooks/send-reorder-emails'
    | '/_authenticated/patient-intakes/$intakeId/'
    | '/_authenticated/supplies/$itemId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksSendReorderEmailsRoute: typeof ApiPublicHooksSendReorderEmailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient-intakes/': {
      id: '/_authenticated/patient-intakes/'
      path: '/patient-intakes'
      fullPath: '/patient-intakes/'
      preLoaderRoute: typeof AuthenticatedPatientIntakesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient-intakes/new': {
      id: '/_authenticated/patient-intakes/new'
      path: '/patient-intakes/new'
      fullPath: '/patient-intakes/new'
      preLoaderRoute: typeof AuthenticatedPatientIntakesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplies/': {
      id: '/_authenticated/supplies/'
      path: '/supplies'
      fullPath: '/supplies/'
      preLoaderRoute: typeof AuthenticatedSuppliesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplies/new': {
      id: '/_authenticated/supplies/new'
      path: '/supplies/new'
      fullPath: '/supplies/new'
      preLoaderRoute: typeof AuthenticatedSuppliesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient-intakes/$intakeId/': {
      id: '/_authenticated/patient-intakes/$intakeId/'
      path: '/patient-intakes/$intakeId'
      fullPath: '/patient-intakes/$intakeId/'
      preLoaderRoute: typeof AuthenticatedPatientIntakesIntakeIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient-intakes/$intakeId/edit': {
      id: '/_authenticated/patient-intakes/$intakeId/edit'
      path: '/patient-intakes/$intakeId/edit'
      fullPath: '/patient-intakes/$intakeId/edit'
      preLoaderRoute: typeof AuthenticatedPatientIntakesIntakeIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplies/$itemId/': {
      id: '/_authenticated/supplies/$itemId/'
      path: '/supplies/$itemId'
      fullPath: '/supplies/$itemId/'
      preLoaderRoute: typeof AuthenticatedSuppliesItemIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplies/$itemId/edit': {
      id: '/_authenticated/supplies/$itemId/edit'
      path: '/supplies/$itemId/edit'
      fullPath: '/supplies/$itemId/edit'
      preLoaderRoute: typeof AuthenticatedSuppliesItemIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/send-reorder-emails': {
      id: '/api/public/hooks/send-reorder-emails'
      path: '/api/public/hooks/send-reorder-emails'
      fullPath: '/api/public/hooks/send-reorder-emails'
      preLoaderRoute: typeof ApiPublicHooksSendReorderEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedPatientIntakesNewRoute: typeof AuthenticatedPatientIntakesNewRoute
  AuthenticatedSuppliesNewRoute: typeof AuthenticatedSuppliesNewRoute
  AuthenticatedPatientIntakesIndexRoute: typeof AuthenticatedPatientIntakesIndexRoute
  AuthenticatedSuppliesIndexRoute: typeof AuthenticatedSuppliesIndexRoute
  AuthenticatedPatientIntakesIntakeIdEditRoute: typeof AuthenticatedPatientIntakesIntakeIdEditRoute
  AuthenticatedSuppliesItemIdEditRoute: typeof AuthenticatedSuppliesItemIdEditRoute
  AuthenticatedPatientIntakesIntakeIdIndexRoute: typeof AuthenticatedPatientIntakesIntakeIdIndexRoute
  AuthenticatedSuppliesItemIdIndexRoute: typeof AuthenticatedSuppliesItemIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedPatientIntakesNewRoute: AuthenticatedPatientIntakesNewRoute,
  AuthenticatedSuppliesNewRoute: AuthenticatedSuppliesNewRoute,
  AuthenticatedPatientIntakesIndexRoute: AuthenticatedPatientIntakesIndexRoute,
  AuthenticatedSuppliesIndexRoute: AuthenticatedSuppliesIndexRoute,
  AuthenticatedPatientIntakesIntakeIdEditRoute:
    AuthenticatedPatientIntakesIntakeIdEditRoute,
  AuthenticatedSuppliesItemIdEditRoute: AuthenticatedSuppliesItemIdEditRoute,
  AuthenticatedPatientIntakesIntakeIdIndexRoute:
    AuthenticatedPatientIntakesIntakeIdIndexRoute,
  AuthenticatedSuppliesItemIdIndexRoute: AuthenticatedSuppliesItemIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksSendReorderEmailsRoute: ApiPublicHooksSendReorderEmailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
